# Generated by Django 5.2.17 on 2026-10-01 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0125_remove_event_core_event_bgmap_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="send_interval",
            field=models.PositiveIntegerField(
                default=5,
                help_text="If using GPS trackers, enter here the upload interval setting of your devices, when using one of the official tracker app, leave the value at 5 seconds",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Live upload interval (seconds)",
            ),
        ),
    ]
