# Generated by Django 5.2.17 on 2026-10-03 06:21

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Club = apps.get_model("core", "Club")
    db_alias = schema_editor.connection.alias

    lines_to_remove = [
        "## GPS Tracking",
        "Follow our events live or replay them later.",
        "*This website is powered by Routechoices.com*",
    ]
    for line in lines_to_remove:
        cc = Club.objects.filter(
            description__contains=line
        )
        for c in cc:
            c.description = c.description.replace(line, "").strip()
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_alter_event_send_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="This text will be displayed on the club site frontpage, use markdown formatting",
            ),
        ),
        migrations.RunPython(forwards_func, lambda *: ...),
    ]
